AspNetCoreNotes/Models/ErrorViewModel.cs
namespace AspNetCoreNotes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetCoreNotes/Models/Note.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace AspNetCoreNotes.Models
{
    public class Note
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Identicon { get; set; }

        public string Body { get; set; }

        public IdentityUser User { get; set; }

        public DateTimeOffset CreatedAt { get; set; }
    }
}

AspNetCoreNotes/Models/NotesSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreNotes.Models
{
    public class NotesSearchViewModel
    {
        public string Filter { get; set; }
    }
}

AspNetCoreNotes/Models/NotesViewModel.cs
using System.Collections.Generic;

namespace AspNetCoreNotes.Models
{
    public class NotesViewModel
    {
        public List<Note> Notes { get; set; }
    }
}

AspNetCoreNotes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreNotes.Models;

namespace AspNetCoreNotes.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetCoreNotes/Controllers/NotesController.cs
using System.Threading.Tasks;
using AspNetCoreNotes.Models;
using AspNetCoreNotes.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreNotes.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly INotesService _notesService;
        private readonly UserManager<IdentityUser> _userManager;

        public NotesController(INotesService notesService, UserManager<IdentityUser> userManager)
        {
            _notesService = notesService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string filter)
        {
            var user = await _userManager.GetUserAsync(User);
            var notes = await _notesService.GetNotesAsync(user.Id, filter);

            var notesViewModel = new NotesViewModel
            {
                Notes = notes
            };

            return View(notesViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var note = await _notesService.GetNoteAsync(id);

            ValidateNote(note, user);

            return View(note);
        }

        public IActionResult Create()
        {
            return View(new Note());
        }

        public async Task<IActionResult> Add(Note note)
        {
            note.User = await _userManager.GetUserAsync(User);
            await _notesService.AddAsync(note);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var note = await _notesService.GetNoteAsync(id);

            ValidateNote(note, user);

            await _notesService.DeleteAsync(note);
            return RedirectToAction(nameof(Index));
        }

        private void ValidateNote(Note note, IdentityUser user)
        {
            if (note == null)
                NotFound();

            if (note.User != user)
                Forbid();
        }
    }
}

AspNetCoreNotes/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AspNetCoreNotes/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AspNetCoreNotes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<p>Реализовать веб-приложение для хранения пользовательских заметок.</p>
<p>Требуемый функционал:</p>
<ul>
    <li>Авторизация пользователя</li>
    <li>Регистрация пользователя</li>
    <li>Просмотр списка заметок</li>
    <li>Просмотр заметки</li>
    <li>Добавление заметки</li>
    <li>Удаление заметки</li>
    <li>Поиск по заметкам</li>
</ul>
<p>Для каждой новой заметки необходимо сгенерировать identicon с помощью https://avatars.dicebear.com посредством http-api сервиса. Полученную картинку сохранить в БД и выводить при просмотре списка заметок и конкретной заметки.</p>
<p>Приложение должно быть реализовано с использованием ASP.NET Core 2.0. Для авторизации использовать Identiy, для доступа к данным Entity Framework Core. Клиентская часть должна быть реализована с использованием Razor.</p>

AspNetCoreNotes/Views/Notes/Create.cshtml
@model Note

@{
    ViewData["Title"] = "Create new note";
}

<form asp-action="Add" method="POST">
    <label asp-for="Title">Title</label>
    <br />
    <input asp-for="Title" />
    <br />
    <label asp-for="Body">Body</label>
    <br />
    <input asp-for="Body" />
    <button type="submit">Add</button>
</form>

AspNetCoreNotes/Views/Notes/Details.cshtml
@using Humanizer
@model Note

@{
    ViewData["Title"] = "Note details";
}

<img src="@Model.Identicon" width="75" height="75" />
<br/>
<label>Title:</label>
<br/>
<label>@Model.Title</label>
<br/>
<label>Created:</label>
<br/>
<label>@Model.CreatedAt.Humanize()</label>
<br/>
<label>Body:</label>
<br/>
<label>@Model.Body</label>

<div class="panel-footer delete-item-form">
    <form asp-action="Delete" asp-route-id="@Model.Id" method="POST">
        <button type="submit">Delete</button>
    </form>
</div>

AspNetCoreNotes/Views/Notes/Index.cshtml
@using Humanizer
@model NotesViewModel


@{
    ViewData["Title"] = "Notes list";
}

<div class="panel-header search-item-form">
    @await Html.PartialAsync("SearchPartial", new NotesSearchViewModel())
</div>

<div class="panel panel-default notes-panel">
    <div class="panel-heading">@ViewData["Title"]</div>

    <table class="table table-hover">
        <thead>
        <tr>
            <td>Identicon</td>
            <td>Title</td>
            <td>Created</td>
        </tr>
        </thead>

        @foreach (var note in Model.Notes)
        {
            <tr>
                <td><img src="@note.Identicon" width="50" height="50"/></td>
                <td><a asp-action="Details" asp-route-id="@note.Id">@note.Title</a></td>
                <td>@note.CreatedAt.Humanize()</td>
            </tr>
        }
    </table>
</div>

<div class="panel-footer add-item-form">
    <form asp-action="Create" method="GET">
        <button type="submit">Create</button>
    </form>
</div>

AspNetCoreNotes/Views/Notes/SearchPartial.cshtml
@model NotesSearchViewModel

<form asp-action="Index" method="GET" asp-route-filter="@Model.Filter">
    <input asp-for="Filter" />
    <button type="submit">Find</button>
</form>

AspNetCoreNotes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreNotes</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspNetCoreNotes</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Notes" asp-action="Index">Notes</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AspNetCoreNotes</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>